### ISSUE TITLE
Microsoft store version is out of date

### ISSUE THREAD

**Issue by Cpn-Neemo** [kochie/touch-type#25]
Firstly, great little app, thank you.

When installing from the Microsoft store the app immediately wants to update but the update seems to be bugged I have attached the error message.

When installing from the release .exe everything seems to work fine.

![image](https://github.com/user-attachments/assets/6cbffab4-6c53-41ef-96f2-7ae9fbfebcae)

If I click restart it pops up and error failed to launch installer. Curiously it works if the newest update is already installed and just updates over the already installed version.

**Comment by kochie** [comment]
Nice thanks, I have a major version bump coming out this week. Just working on getting it out the door right now. That should fix this issue.
